services:
  minecraft:
    image: itzg/minecraft-server:java21
    container_name: minecraft-paper-1.21.8
    tty: true
    stdin_open: true
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.21.8"
      PAPER_DOWNLOAD_URL: "https://fill-data.papermc.io/v1/objects/8de7c52c3b02403503d16fac58003f1efef7dd7a0256786843927fa92ee57f1e/paper-1.21.8-60.jar"
      MEMORY: "2G"
      # Permite conexoes sem conta premium (ajustavel conforme necessario)
      ONLINE_MODE: "FALSE"
      ENFORCE_SECURE_PROFILE: "FALSE"
    ports:
      - "25565:25565"
      - "25575:25575"
    volumes:
      - ./data:/data
      - ./plugins:/plugins:ro
    restart: unless-stopped
